version: '3'
services:
  calculator-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_HOST=http://localhost:3001/truenorth